apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: default
  # annotations:
  #   kubernetes.io/service-account.name: "sa-name"
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  db_name: amFkZWxtb3VsYQ==
  db_user: YWJkZWxhbGk=
  db_passwd: YWJkZWxhbGk=
  