apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: default
  labels:
    app: react
spec:
  type: ClusterIP
  selector:
    app: react
  ports:
   - name: react
     protocol: TCP
     port: 80
     targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
  labels:
    app: flask
spec:
  type: ClusterIP
  selector:
    app: flask
  ports:
   - name: flask
     protocol: TCP
     port: 8000
     targetPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: default
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
   - name: mysql
     protocol: TCP
     port: 3306
     targetPort: 3306